### ISSUE TITLE
Flyway 4.0 commandline creates empty metadata table

### ISSUE THREAD

**Issue by dhoer** [dhoer/flyway_percona#1]
http://stackoverflow.com/questions/36416674/flyway-4-0-commandline-creates-empty-metadata-table

@axelfontaine All greened up!
Thanks

**Comment by dhoer** [comment]
@axelfontaine does the following properly explain the expected behavior when mysql connector/j is downloaded?

`mysql_driver` - MariaDB Connector/J driver is the default driver for MySQL. Set true to download and install MySQL Connector/J driver under drivers directory. This will then become the default driver for MySQL connections. Default: `false`.

**Comment by axelfontaine** [comment]
@dhoer Correct. With both the MariaDB and MySQL drivers present, Flyway will use the MySQL one for MySQL and Percona connections (jdbc:mysql:... urls) and the MariaDB one for MariaDB connections (jdbc:mariadb:... urls)

**Comment by dhoer** [comment]
@axelfontaine Thank you!

@akrapfl 
I released chef flywaydb 5.1.0 cookbook that allows for install mysql driver:
https://supermarket.chef.io/cookbooks/flywaydb

This is the verbiage I went with:
- `mysql_driver` - MariaDB Connector/J driver is the default driver 
  for _jdbc:mysql:_ connections.  Set to true to download and install 
  MySQL Connector/J driver under `drivers` directory. This will then 
  become the default driver for _jdbc:mysql:_ connections. 
  Default: `false`.

**Comment by dhoer** [comment]
@axelfontaine @akrapfl Alex, We have seen other issues related to the MariaDB driver 1.3.6 version. I was informed by one of my teammates that this driver has a lot of bugs and releases regularly to try to address them.  We tried the latest 1.4.4 version of MariaDB and it fixed all of the issues we were seeing.  Is it possible to get a release of flyway with this MariaDB version?
